// <auto-generated />
using System;
using System.Collections.Generic;
using Kapea.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kapea.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(KapeaDbContext))]
    [Migration("20260923172411_RemoveMisreadKrakenSwaps")]
    partial class RemoveMisreadKrakenSwaps
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Kapea.Domain.Accounts.Platform", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<bool>("BuiltIn")
                        .HasColumnType("bit");

                    b.Property<decimal>("FeeRate")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("FixedFee")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(28, 8)
                        .HasColumnType("decimal(28,8)")
                        .HasDefaultValue(0m);

                    b.Property<string>("ImportKind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Code");

                    b.ToTable("Platforms", (string)null);

                    b.HasData(
                        new
                        {
                            Code = "Xtb",
                            BuiltIn = true,
                            ImportKind = "File",
                            Name = "XTB"
                        },
                        new
                        {
                            Code = "Kraken",
                            BuiltIn = true,
                            ImportKind = "Api",
                            Name = "Kraken"
                        },
                        new
                        {
                            Code = "Bit2Me",
                            BuiltIn = true,
                            ImportKind = "Api",
                            Name = "Bit2Me"
                        });
                });

            modelBuilder.Entity("Kapea.Domain.Accounts.PlatformAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("BaseCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Accounts", (string)null);
                });

            modelBuilder.Entity("Kapea.Domain.Assets.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CanonicalSymbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<string>("Isin")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.HasKey("Id");

                    b.HasIndex("CanonicalSymbol", "Class")
                        .IsUnique();

                    b.ToTable("Assets", (string)null);
                });

            modelBuilder.Entity("Kapea.Domain.Calculation.CalculationInconsistency", b =>
                {
                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("MissingQuantity")
                        .HasPrecision(38, 18)
                        .HasColumnType("decimal(38,18)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "OccurredAt", "Kapea.Domain.Calculation.CalculationInconsistency.OccurredAt#Occurrence", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTimeOffset>("Instant")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("OccurredAt");

                            b1.Property<string>("SourceTimeZoneId")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)")
                                .HasColumnName("OccurredAtTimeZoneId");
                        });

                    b.HasKey("TransactionId", "Kind");

                    b.HasIndex("UserId", "AssetId");

                    b.ToTable("CalculationInconsistencies", (string)null);
                });

            modelBuilder.Entity("Kapea.Domain.Calculation.CapitalIncome", b =>
                {
                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AssetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "GrossAmountInEuros", "Kapea.Domain.Calculation.CapitalIncome.GrossAmountInEuros#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasPrecision(28, 8)
                                .HasColumnType("decimal(28,8)")
                                .HasColumnName("GrossAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("GrossCurrency");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "ReceivedAt", "Kapea.Domain.Calculation.CapitalIncome.ReceivedAt#Occurrence", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTimeOffset>("Instant")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("ReceivedAt");

                            b1.Property<string>("SourceTimeZoneId")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)")
                                .HasColumnName("ReceivedAtTimeZoneId");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "WithholdingInEuros", "Kapea.Domain.Calculation.CapitalIncome.WithholdingInEuros#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasPrecision(28, 8)
                                .HasColumnType("decimal(28,8)")
                                .HasColumnName("WithholdingAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("WithholdingCurrency");
                        });

                    b.HasKey("TransactionId");

                    b.HasIndex("UserId", "AssetId");

                    b.ToTable("CapitalIncomes", (string)null);
                });

            modelBuilder.Entity("Kapea.Domain.Calculation.ConsumedLot", b =>
                {
                    b.Property<Guid>("DisposalTransactionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LotId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AcquisitionTransactionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(38, 18)
                        .HasColumnType("decimal(38,18)");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "AcquiredAt", "Kapea.Domain.Calculation.ConsumedLot.AcquiredAt#Occurrence", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTimeOffset>("Instant")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("AcquiredAt");

                            b1.Property<string>("SourceTimeZoneId")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)")
                                .HasColumnName("AcquiredAtTimeZoneId");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "AcquisitionCostInEuros", "Kapea.Domain.Calculation.ConsumedLot.AcquisitionCostInEuros#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasPrecision(28, 8)
                                .HasColumnType("decimal(28,8)")
                                .HasColumnName("AcquisitionCostAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("AcquisitionCostCurrency");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "ProceedsInEuros", "Kapea.Domain.Calculation.ConsumedLot.ProceedsInEuros#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasPrecision(28, 8)
                                .HasColumnType("decimal(28,8)")
                                .HasColumnName("ProceedsAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("ProceedsCurrency");
                        });

                    b.HasKey("DisposalTransactionId", "LotId");

                    b.ToTable("RealizedResultLots", (string)null);
                });

            modelBuilder.Entity("Kapea.Domain.Calculation.RealizedResult", b =>
                {
                    b.Property<Guid>("DisposalTransactionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(38, 18)
                        .HasColumnType("decimal(38,18)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "AcquisitionCostInEuros", "Kapea.Domain.Calculation.RealizedResult.AcquisitionCostInEuros#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasPrecision(28, 8)
                                .HasColumnType("decimal(28,8)")
                                .HasColumnName("AcquisitionCostAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("AcquisitionCostCurrency");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "DisposedAt", "Kapea.Domain.Calculation.RealizedResult.DisposedAt#Occurrence", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTimeOffset>("Instant")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("DisposedAt");

                            b1.Property<string>("SourceTimeZoneId")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)")
                                .HasColumnName("DisposedAtTimeZoneId");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "ProceedsInEuros", "Kapea.Domain.Calculation.RealizedResult.ProceedsInEuros#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasPrecision(28, 8)
                                .HasColumnType("decimal(28,8)")
                                .HasColumnName("ProceedsAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("ProceedsCurrency");
                        });

                    b.HasKey("DisposalTransactionId");

                    b.HasIndex("UserId", "AssetId");

                    b.ToTable("RealizedResults", (string)null);
                });

            modelBuilder.Entity("Kapea.Domain.Credentials.BrokerCredential", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("InvalidReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset?>("LastSynchronizedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTimeOffset?>("RotatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Scopes")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("SecretName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "AccountId");

                    b.ToTable("BrokerCredentials", (string)null);
                });

            modelBuilder.Entity("Kapea.Domain.Exchange.DailyRate", b =>
                {
                    b.Property<string>("Currency")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("UnitsPerEuro")
                        .HasPrecision(28, 12)
                        .HasColumnType("decimal(28,12)");

                    b.HasKey("Currency", "Date");

                    b.ToTable("DailyRates", (string)null);
                });

            modelBuilder.Entity("Kapea.Domain.Ideas.ExternalIdea", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AssetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Note")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTime>("PublishedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ResolvedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Url")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Entry", "Kapea.Domain.Ideas.ExternalIdea.Entry#Money", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .HasPrecision(28, 8)
                                .HasColumnType("decimal(28,8)")
                                .HasColumnName("EntryAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("EntryCurrency");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "StopLoss", "Kapea.Domain.Ideas.ExternalIdea.StopLoss#Money", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .HasPrecision(28, 8)
                                .HasColumnType("decimal(28,8)")
                                .HasColumnName("StopAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("StopCurrency");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Target", "Kapea.Domain.Ideas.ExternalIdea.Target#Money", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .HasPrecision(28, 8)
                                .HasColumnType("decimal(28,8)")
                                .HasColumnName("TargetAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("TargetCurrency");
                        });

                    b.HasKey("Id");

                    b.HasIndex("SourceId");

                    b.HasIndex("UserId", "PublishedOn");

                    b.ToTable("ExternalIdeas", (string)null);
                });

            modelBuilder.Entity("Kapea.Domain.Ideas.IdeaSource", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Channel")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset?>("LastSeenAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastSeenUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Name")
                        .IsUnique();

                    b.ToTable("IdeaSources", (string)null);
                });

            modelBuilder.Entity("Kapea.Domain.Identity.ExternalIdentity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("LastSignedInAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("LinkedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("Provider", "Subject")
                        .IsUnique();

                    b.ToTable("ExternalIdentities", (string)null);
                });

            modelBuilder.Entity("Kapea.Domain.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<DateTimeOffset?>("LastSignedInAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Kapea.Domain.Import.ImportRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("CoversUntil")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("FileName")
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<int>("NonFinancialRecords")
                        .HasColumnType("int");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<Guid?>("ProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("ProfileVersion")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "AccountId", "Status");

                    b.ToTable("ImportRuns", (string)null);
                });

            modelBuilder.Entity("Kapea.Domain.Import.StagedRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("ImportRunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NaturalId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RawContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("RowNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ImportRunId", "Outcome");

                    b.ToTable("ImportStagedRecords", (string)null);
                });

            modelBuilder.Entity("Kapea.Domain.ImportProfiles.ImportProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("BuiltIn")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("Id");

                    b.HasIndex("Platform");

                    b.ToTable("ImportProfiles", (string)null);
                });

            modelBuilder.Entity("Kapea.Domain.Journal.DecisionNote", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SignalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<Guid?>("TransactionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("WrittenAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("SignalId");

                    b.HasIndex("TransactionId");

                    b.HasIndex("UserId", "WrittenAt");

                    b.ToTable("DecisionNotes", (string)null);
                });

            modelBuilder.Entity("Kapea.Domain.Lots.Lot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("OriginalQuantity")
                        .HasPrecision(38, 18)
                        .HasColumnType("decimal(38,18)");

                    b.Property<decimal>("RemainingQuantity")
                        .HasPrecision(38, 18)
                        .HasColumnType("decimal(38,18)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "AcquiredAt", "Kapea.Domain.Lots.Lot.AcquiredAt#Occurrence", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTimeOffset>("Instant")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("AcquiredAt");

                            b1.Property<string>("SourceTimeZoneId")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)")
                                .HasColumnName("AcquiredAtTimeZoneId");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "AcquisitionCost", "Kapea.Domain.Lots.Lot.AcquisitionCost#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasPrecision(28, 8)
                                .HasColumnType("decimal(28,8)")
                                .HasColumnName("AcquisitionCostAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("AcquisitionCostCurrency");
                        });

                    b.HasKey("Id");

                    b.HasIndex("UserId", "AssetId");

                    b.ToTable("Lots", (string)null);
                });

            modelBuilder.Entity("Kapea.Domain.MarketData.DailyPrice", b =>
                {
                    b.Property<Guid>("AssetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PriceInEuros")
                        .HasPrecision(28, 12)
                        .HasColumnType("decimal(28,12)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("AssetId", "Date");

                    b.ToTable("DailyPrices", (string)null);
                });

            modelBuilder.Entity("Kapea.Domain.Strategies.EmittedSignal", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("StrategyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("StrategyVersion")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "PriceInEuros", "Kapea.Domain.Strategies.EmittedSignal.PriceInEuros#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasPrecision(28, 8)
                                .HasColumnType("decimal(28,8)")
                                .HasColumnName("PriceAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("PriceCurrency");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "StopLoss", "Kapea.Domain.Strategies.EmittedSignal.StopLoss#Money", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .HasPrecision(28, 8)
                                .HasColumnType("decimal(28,8)")
                                .HasColumnName("StopAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("StopCurrency");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Target", "Kapea.Domain.Strategies.EmittedSignal.Target#Money", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .HasPrecision(28, 8)
                                .HasColumnType("decimal(28,8)")
                                .HasColumnName("TargetAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("TargetCurrency");
                        });

                    b.HasKey("Id");

                    b.HasIndex("Fingerprint")
                        .IsUnique();

                    b.HasIndex("UserId", "Date");

                    b.ToTable("EmittedSignals", (string)null);
                });

            modelBuilder.Entity("Kapea.Domain.Strategies.Strategy", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Name")
                        .IsUnique();

                    b.ToTable("Strategies", (string)null);
                });

            modelBuilder.Entity("Kapea.Domain.Transactions.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdjustmentReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("AmountIsEstimated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid?>("AssetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DistinctFrom")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(38, 18)
                        .HasColumnType("decimal(38,18)");

                    b.Property<DateTimeOffset?>("RegisteredAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("RevisedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("SettledInCash")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("VoidReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset?>("VoidedAt")
                        .HasColumnType("datetimeoffset");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Fee", "Kapea.Domain.Transactions.Transaction.Fee#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasPrecision(28, 8)
                                .HasColumnType("decimal(28,8)")
                                .HasColumnName("FeeAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("FeeCurrency");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "GrossAmount", "Kapea.Domain.Transactions.Transaction.GrossAmount#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasPrecision(28, 8)
                                .HasColumnType("decimal(28,8)")
                                .HasColumnName("GrossAmountAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("GrossAmountCurrency");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "OccurredAt", "Kapea.Domain.Transactions.Transaction.OccurredAt#Occurrence", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTimeOffset>("Instant")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("OccurredAt");

                            b1.Property<string>("SourceTimeZoneId")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)")
                                .HasColumnName("OccurredAtTimeZoneId");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "UnitPrice", "Kapea.Domain.Transactions.Transaction.UnitPrice#Money", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .HasPrecision(28, 8)
                                .HasColumnType("decimal(28,8)")
                                .HasColumnName("UnitPriceAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("UnitPriceCurrency");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "WithholdingTax", "Kapea.Domain.Transactions.Transaction.WithholdingTax#Money", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .HasPrecision(28, 8)
                                .HasColumnType("decimal(28,8)")
                                .HasColumnName("WithholdingAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("WithholdingCurrency");
                        });

                    b.HasKey("Id");

                    b.HasIndex("UserId", "AccountId");

                    b.HasIndex("UserId", "AssetId");

                    b.ToTable("Transactions", (string)null);
                });

            modelBuilder.Entity("Kapea.Domain.Transfers.InternalTransfer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DestinationAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IncomingTransactionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OutgoingTransactionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("ProposedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("ReceivedQuantity")
                        .HasPrecision(38, 18)
                        .HasColumnType("decimal(38,18)");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("SentQuantity")
                        .HasPrecision(38, 18)
                        .HasColumnType("decimal(38,18)");

                    b.Property<Guid>("SourceAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OutgoingTransactionId", "IncomingTransactionId")
                        .IsUnique();

                    b.HasIndex("UserId", "Status");

                    b.ToTable("InternalTransfers", (string)null);
                });

            modelBuilder.Entity("Kapea.Infrastructure.Persistence.AccountSyncLockRow", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("AcquiredAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("Token")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AccountId");

                    b.ToTable("AccountSyncLocks", (string)null);
                });

            modelBuilder.Entity("Kapea.Domain.Calculation.ConsumedLot", b =>
                {
                    b.HasOne("Kapea.Domain.Calculation.RealizedResult", null)
                        .WithMany("ConsumedLots")
                        .HasForeignKey("DisposalTransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kapea.Domain.Identity.ExternalIdentity", b =>
                {
                    b.HasOne("Kapea.Domain.Identity.User", null)
                        .WithMany("Identities")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kapea.Domain.Import.StagedRecord", b =>
                {
                    b.HasOne("Kapea.Domain.Import.ImportRun", null)
                        .WithMany("Records")
                        .HasForeignKey("ImportRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kapea.Domain.ImportProfiles.ImportProfile", b =>
                {
                    b.OwnsMany("Kapea.Domain.ImportProfiles.ImportProfileVersion", "_versions", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<bool>("AmountIsAlwaysPositive")
                                .HasColumnType("bit");

                            b1.Property<bool>("AmountIsNetOfFee")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bit")
                                .HasDefaultValue(false);

                            b1.Property<string>("AmountSource")
                                .IsRequired()
                                .HasMaxLength(24)
                                .HasColumnType("nvarchar(24)");

                            b1.Property<DateTimeOffset>("CreatedAt")
                                .HasColumnType("datetimeoffset");

                            b1.Property<string>("DecimalConvention")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("nvarchar(16)");

                            b1.Property<string>("Delimiter")
                                .IsRequired()
                                .HasMaxLength(1)
                                .HasColumnType("nvarchar(1)");

                            b1.Property<string>("FixedAssetClass")
                                .HasMaxLength(24)
                                .HasColumnType("nvarchar(24)");

                            b1.Property<string>("FixedCurrency")
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)");

                            b1.Property<int>("Number")
                                .HasColumnType("int");

                            b1.Property<Guid>("ProfileId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("RowShape")
                                .IsRequired()
                                .HasMaxLength(24)
                                .HasColumnType("nvarchar(24)");

                            b1.Property<string>("TimeZoneId")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)");

                            b1.Property<string>("_columns")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Columns");

                            b1.Property<string>("_concepts")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Concepts");

                            b1.Property<string>("_dateFormats")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("DateFormats");

                            b1.Property<string>("_nonFinancialConcepts")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("NonFinancialConcepts");

                            b1.Property<string>("_recognizedHeaders")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("RecognizedHeaders");

                            b1.HasKey("Id");

                            b1.HasIndex("Number");

                            b1.HasIndex("ProfileId");

                            b1.ToTable("ImportProfileVersions", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ProfileId");
                        });

                    b.Navigation("_versions");
                });

            modelBuilder.Entity("Kapea.Domain.Strategies.Strategy", b =>
                {
                    b.OwnsMany("Kapea.Domain.Strategies.StrategyVersion", "Versions", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTimeOffset>("CreatedAt")
                                .HasColumnType("datetimeoffset");

                            b1.Property<string>("Entry")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Exit")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("Number")
                                .HasColumnType("int");

                            b1.Property<string>("StopLoss")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<Guid>("StrategyId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Target")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("Id");

                            b1.HasIndex("StrategyId", "Number")
                                .IsUnique();

                            b1.ToTable("StrategyVersions", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("StrategyId");
                        });

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("Kapea.Domain.Transactions.Transaction", b =>
                {
                    b.OwnsOne("Kapea.Domain.Exchange.ExchangeRate", "AppliedExchangeRate", b1 =>
                        {
                            b1.Property<Guid>("TransactionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("RateCurrency");

                            b1.Property<DateTime>("RateDate")
                                .HasColumnType("datetime2")
                                .HasColumnName("RateDate");

                            b1.Property<DateTime>("RequestedDate")
                                .HasColumnType("datetime2")
                                .HasColumnName("RateRequestedDate");

                            b1.Property<string>("Source")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("nvarchar(32)")
                                .HasColumnName("RateSource");

                            b1.Property<decimal>("UnitsPerEuro")
                                .HasPrecision(28, 12)
                                .HasColumnType("decimal(28,12)")
                                .HasColumnName("RateUnitsPerEuro");

                            b1.HasKey("TransactionId");

                            b1.ToTable("Transactions");

                            b1.WithOwner()
                                .HasForeignKey("TransactionId");
                        });

                    b.OwnsOne("Kapea.Domain.Transactions.TransactionSource", "Source", b1 =>
                        {
                            b1.Property<Guid>("TransactionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Fingerprint")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)")
                                .HasColumnName("Fingerprint");

                            b1.Property<Guid?>("ImportRunId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("ImportRunId");

                            b1.Property<string>("NaturalId")
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("SourceNaturalId");

                            b1.Property<Guid?>("ProfileId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("SourceProfileId");

                            b1.Property<int?>("ProfileVersion")
                                .HasColumnType("int")
                                .HasColumnName("SourceProfileVersion");

                            b1.Property<string>("RawContent")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int?>("RowNumber")
                                .HasColumnType("int")
                                .HasColumnName("SourceRowNumber");

                            b1.HasKey("TransactionId");

                            b1.HasIndex("Fingerprint");

                            b1.ToTable("Transactions");

                            b1.WithOwner()
                                .HasForeignKey("TransactionId");
                        });

                    b.Navigation("AppliedExchangeRate");

                    b.Navigation("Source")
                        .IsRequired();
                });

            modelBuilder.Entity("Kapea.Domain.Calculation.RealizedResult", b =>
                {
                    b.Navigation("ConsumedLots");
                });

            modelBuilder.Entity("Kapea.Domain.Identity.User", b =>
                {
                    b.Navigation("Identities");
                });

            modelBuilder.Entity("Kapea.Domain.Import.ImportRun", b =>
                {
                    b.Navigation("Records");
                });
#pragma warning restore 612, 618
        }
    }
}
