// <auto-generated />
using System;
using System.Collections.Generic;
using Kapea.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kapea.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(KapeaDbContext))]
    [Migration("20260908192741_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Kapea.Domain.Accounts.PlatformAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("BaseCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Accounts", (string)null);
                });

            modelBuilder.Entity("Kapea.Domain.Assets.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CanonicalSymbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<string>("Isin")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.HasKey("Id");

                    b.HasIndex("CanonicalSymbol", "Class")
                        .IsUnique();

                    b.ToTable("Assets", (string)null);
                });

            modelBuilder.Entity("Kapea.Domain.Calculation.CapitalIncome", b =>
                {
                    b.Property<Guid>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AssetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "GrossAmountInEuros", "Kapea.Domain.Calculation.CapitalIncome.GrossAmountInEuros#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasPrecision(28, 8)
                                .HasColumnType("decimal(28,8)")
                                .HasColumnName("GrossAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("GrossCurrency");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "ReceivedAt", "Kapea.Domain.Calculation.CapitalIncome.ReceivedAt#Occurrence", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTimeOffset>("Instant")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("ReceivedAt");

                            b1.Property<string>("SourceTimeZoneId")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)")
                                .HasColumnName("ReceivedAtTimeZoneId");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "WithholdingInEuros", "Kapea.Domain.Calculation.CapitalIncome.WithholdingInEuros#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasPrecision(28, 8)
                                .HasColumnType("decimal(28,8)")
                                .HasColumnName("WithholdingAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("WithholdingCurrency");
                        });

                    b.HasKey("TransactionId");

                    b.HasIndex("UserId", "AssetId");

                    b.ToTable("CapitalIncomes", (string)null);
                });

            modelBuilder.Entity("Kapea.Domain.Calculation.ConsumedLot", b =>
                {
                    b.Property<Guid>("DisposalTransactionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LotId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AcquisitionTransactionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(38, 18)
                        .HasColumnType("decimal(38,18)");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "AcquiredAt", "Kapea.Domain.Calculation.ConsumedLot.AcquiredAt#Occurrence", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTimeOffset>("Instant")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("AcquiredAt");

                            b1.Property<string>("SourceTimeZoneId")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)")
                                .HasColumnName("AcquiredAtTimeZoneId");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "AcquisitionCostInEuros", "Kapea.Domain.Calculation.ConsumedLot.AcquisitionCostInEuros#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasPrecision(28, 8)
                                .HasColumnType("decimal(28,8)")
                                .HasColumnName("AcquisitionCostAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("AcquisitionCostCurrency");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "ProceedsInEuros", "Kapea.Domain.Calculation.ConsumedLot.ProceedsInEuros#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasPrecision(28, 8)
                                .HasColumnType("decimal(28,8)")
                                .HasColumnName("ProceedsAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("ProceedsCurrency");
                        });

                    b.HasKey("DisposalTransactionId", "LotId");

                    b.ToTable("RealizedResultLots", (string)null);
                });

            modelBuilder.Entity("Kapea.Domain.Calculation.RealizedResult", b =>
                {
                    b.Property<Guid>("DisposalTransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(38, 18)
                        .HasColumnType("decimal(38,18)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "AcquisitionCostInEuros", "Kapea.Domain.Calculation.RealizedResult.AcquisitionCostInEuros#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasPrecision(28, 8)
                                .HasColumnType("decimal(28,8)")
                                .HasColumnName("AcquisitionCostAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("AcquisitionCostCurrency");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "DisposedAt", "Kapea.Domain.Calculation.RealizedResult.DisposedAt#Occurrence", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTimeOffset>("Instant")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("DisposedAt");

                            b1.Property<string>("SourceTimeZoneId")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)")
                                .HasColumnName("DisposedAtTimeZoneId");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "ProceedsInEuros", "Kapea.Domain.Calculation.RealizedResult.ProceedsInEuros#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasPrecision(28, 8)
                                .HasColumnType("decimal(28,8)")
                                .HasColumnName("ProceedsAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("ProceedsCurrency");
                        });

                    b.HasKey("DisposalTransactionId");

                    b.HasIndex("UserId", "AssetId");

                    b.ToTable("RealizedResults", (string)null);
                });

            modelBuilder.Entity("Kapea.Domain.Exchange.DailyRate", b =>
                {
                    b.Property<string>("Currency")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("UnitsPerEuro")
                        .HasPrecision(28, 12)
                        .HasColumnType("decimal(28,12)");

                    b.HasKey("Currency", "Date");

                    b.ToTable("DailyRates", (string)null);
                });

            modelBuilder.Entity("Kapea.Domain.Lots.Lot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("OriginalQuantity")
                        .HasPrecision(38, 18)
                        .HasColumnType("decimal(38,18)");

                    b.Property<decimal>("RemainingQuantity")
                        .HasPrecision(38, 18)
                        .HasColumnType("decimal(38,18)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "AcquiredAt", "Kapea.Domain.Lots.Lot.AcquiredAt#Occurrence", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTimeOffset>("Instant")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("AcquiredAt");

                            b1.Property<string>("SourceTimeZoneId")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)")
                                .HasColumnName("AcquiredAtTimeZoneId");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "AcquisitionCost", "Kapea.Domain.Lots.Lot.AcquisitionCost#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasPrecision(28, 8)
                                .HasColumnType("decimal(28,8)")
                                .HasColumnName("AcquisitionCostAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("AcquisitionCostCurrency");
                        });

                    b.HasKey("Id");

                    b.HasIndex("UserId", "AssetId");

                    b.ToTable("Lots", (string)null);
                });

            modelBuilder.Entity("Kapea.Domain.Transactions.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdjustmentReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("AssetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(38, 18)
                        .HasColumnType("decimal(38,18)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Fee", "Kapea.Domain.Transactions.Transaction.Fee#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasPrecision(28, 8)
                                .HasColumnType("decimal(28,8)")
                                .HasColumnName("FeeAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("FeeCurrency");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "GrossAmount", "Kapea.Domain.Transactions.Transaction.GrossAmount#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasPrecision(28, 8)
                                .HasColumnType("decimal(28,8)")
                                .HasColumnName("GrossAmountAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("GrossAmountCurrency");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "OccurredAt", "Kapea.Domain.Transactions.Transaction.OccurredAt#Occurrence", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTimeOffset>("Instant")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("OccurredAt");

                            b1.Property<string>("SourceTimeZoneId")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)")
                                .HasColumnName("OccurredAtTimeZoneId");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "UnitPrice", "Kapea.Domain.Transactions.Transaction.UnitPrice#Money", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .HasPrecision(28, 8)
                                .HasColumnType("decimal(28,8)")
                                .HasColumnName("UnitPriceAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("UnitPriceCurrency");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "WithholdingTax", "Kapea.Domain.Transactions.Transaction.WithholdingTax#Money", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .HasPrecision(28, 8)
                                .HasColumnType("decimal(28,8)")
                                .HasColumnName("WithholdingAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("WithholdingCurrency");
                        });

                    b.HasKey("Id");

                    b.HasIndex("UserId", "AccountId");

                    b.HasIndex("UserId", "AssetId");

                    b.ToTable("Transactions", (string)null);
                });

            modelBuilder.Entity("Kapea.Domain.Calculation.ConsumedLot", b =>
                {
                    b.HasOne("Kapea.Domain.Calculation.RealizedResult", null)
                        .WithMany("ConsumedLots")
                        .HasForeignKey("DisposalTransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kapea.Domain.Transactions.Transaction", b =>
                {
                    b.OwnsOne("Kapea.Domain.Exchange.ExchangeRate", "AppliedExchangeRate", b1 =>
                        {
                            b1.Property<Guid>("TransactionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("RateCurrency");

                            b1.Property<DateTime>("RateDate")
                                .HasColumnType("datetime2")
                                .HasColumnName("RateDate");

                            b1.Property<DateTime>("RequestedDate")
                                .HasColumnType("datetime2")
                                .HasColumnName("RateRequestedDate");

                            b1.Property<string>("Source")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("nvarchar(32)")
                                .HasColumnName("RateSource");

                            b1.Property<decimal>("UnitsPerEuro")
                                .HasPrecision(28, 12)
                                .HasColumnType("decimal(28,12)")
                                .HasColumnName("RateUnitsPerEuro");

                            b1.HasKey("TransactionId");

                            b1.ToTable("Transactions");

                            b1.WithOwner()
                                .HasForeignKey("TransactionId");
                        });

                    b.OwnsOne("Kapea.Domain.Transactions.TransactionSource", "Source", b1 =>
                        {
                            b1.Property<Guid>("TransactionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Fingerprint")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)")
                                .HasColumnName("Fingerprint");

                            b1.Property<Guid?>("ImportRunId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("ImportRunId");

                            b1.Property<string>("NaturalId")
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("SourceNaturalId");

                            b1.Property<int?>("RowNumber")
                                .HasColumnType("int")
                                .HasColumnName("SourceRowNumber");

                            b1.HasKey("TransactionId");

                            b1.HasIndex("Fingerprint");

                            b1.ToTable("Transactions");

                            b1.WithOwner()
                                .HasForeignKey("TransactionId");
                        });

                    b.Navigation("AppliedExchangeRate");

                    b.Navigation("Source")
                        .IsRequired();
                });

            modelBuilder.Entity("Kapea.Domain.Calculation.RealizedResult", b =>
                {
                    b.Navigation("ConsumedLots");
                });
#pragma warning restore 612, 618
        }
    }
}
